services:
  jenkins:
    build:
      context: .
      dockerfile: newdockerfile 
    container_name: custom-jenkins
    ports:
      - "8080:8080"     # Jenkins web interface
      - "50000:50000"   # Jenkins agent communication
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    restart: unless-stopped

volumes:
  jenkins_home:
