pipeline{
	agent any
        stages{
        	stage('Test'){
        		steps{
                		sh 'sleep 3'
                	}
        	}		
       
                stage('Build'){
                	steps{
                        	sh 'sleep 2'
 
                        }
                }
                stage('Deploy'){
                	input{
                        	message "Approve the Deployment"
                                ok "Approve"
                                submitter "Admins"
                        }
                        steps{
                        	echo "Deployed"
                        }
                }
                stage('clean') {
                	steps{
                        	echo "workspace cleaned"
                        }
                }
        }
}
