pipeline{
	agent any 
        options{
        	disableConcurrentBuilds()
                retry(2)
        }
        stages{
        	stage('sleep for 10s'){
                	options{
                        	timeout(time: 5, unit: 'SECONDS')
                        }
                        steps{
                        	sh 'sleep 10; true'
                        }
                }
                stage('Explicit errors'){
                	steps{
                        	sh 'exit 1'
                        }
                }
        }
}
